# topology
lm_type: lstm
n_units: 1024
n_projs: 0
n_layers: 4  ###
emb_dim: 1024
n_units_null_context: 0
tie_embedding: true
residual: true
use_glu: true
# optimization
batch_size: 128
bptt: 200
optimizer: adam
n_epochs: 60
convert_to_sgd_epoch: 100
print_step: 400
lr: 1e-3
lr_decay_start_epoch: 5
lr_decay_rate: 0.95  ###
lr_decay_patient_n_epochs: 0
lr_decay_type: always
early_stop_patient_n_epochs: 5
eval_start_epoch: 1
# initialization
param_init: 0.05
# regularization
clip_grad_norm: 1.0
dropout_in: 0.2
dropout_hidden: 0.2
dropout_out: 0.0
weight_decay: 1e-6
lsm_prob: 0.0  ###
adaptive_softmax: false
