param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  corpus: librispeech
  label_type: word_freq5
  label_type_sub: character
  data_size: 100h
  num_classes: 11735
  num_classes_sub: 28

  # features
  feature: fbank
  save_format: numpy
  input_channel: 40
  use_delta: True
  use_double_delta: True
  splice: 1
  num_stack: 3
  num_skip: 3
  dynamic_batching: True

  # topology
  model_type: hierarchical_ctc
  encoder_type: lstm
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  poolings: []
  batch_norm: False
  encoder_bidirectional: True
  encoder_residual: False
  encoder_dense_residual: False
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 5
  encoder_num_layers_sub: 4
  subsample_list:
    - False
    - False
    - False
    - False
    - False
  subsample_type: drop
  fc_list: []

  # optimization
  batch_size: 32
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 80
  convert_to_sgd_epoch: 70
  pretrain_stage: False

  # initialization
  parameter_init_distribution: uniform
  parameter_init: 0.1
  recurrent_weight_orthogonal: False
  init_forget_gate_bias_with_one: True
  char_init: False

  # regularization
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout_input: 0
  dropout_encoder: 0.2
  weight_decay: 1e-6
  logits_temperature: 1
  label_smoothing_prob: 0
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 5
  decay_rate: 0.9
  decay_patient_epoch: 1
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 5
  print_step: 200

  # MTL
  main_loss_weight: 0.8
  curriculum_training: False
