# topology
lm_type: lstm
n_units: 16
n_projs: 8
n_layers: 2
emb_dim: 16
n_units_null_context: 0
tie_embedding: true
residual: true
use_glu: true
# optimization
batch_size: 1
bptt: 10
optimizer: adam
n_epochs: 4
convert_to_sgd_epoch: 100
print_step: 1
lr: 1e-3
lr_decay_start_epoch: 2
lr_decay_rate: 0.9
lr_decay_patient_n_epochs: 0
lr_decay_type: always
early_stop_patient_n_epochs: 2
eval_start_epoch: 1
# initialization
param_init: 0.05
# regularization
clip_grad_norm: 1.0
dropout_in: 0.1
dropout_hidden: 0.1
dropout_out: 0.1
weight_decay: 1e-6
lsm_prob: 0.1
adaptive_softmax: false
