# topology
lm_type: transformer_xl
transformer_d_model: 8
transformer_d_ff: 32
n_layers: 2
transformer_n_heads: 4
tie_embedding: true
# optimization
batch_size: 1
bptt: 10
mem_len: 10
optimizer: noam
n_epochs: 4
convert_to_sgd_epoch: 100
print_step: 1
lr_factor: 1.0
early_stop_patient_n_epochs: 2
eval_start_epoch: 1
warmup_n_steps: 2
accum_grad_n_steps: 2
# regularization
clip_grad_norm: 1.0
dropout_in: 0.1
dropout_hidden: 0.1
dropout_out: 0.1
dropout_att: 0.1
dropout_layer: 0.1
weight_decay: 1e-6
lsm_prob: 0.1
adaptive_softmax: false
