### topology
n_stacks: 1
n_skips: 1
max_n_frames: 1600
conv_in_channel: 1
conv_channels: "32_32"
conv_kernel_sizes: "(3,3)_(3,3)"
conv_strides: "(1,1)_(1,1)"
conv_poolings: "(2,2)_(2,2)"
conv_batch_norm: false
subsample: "1_1_1_1_1"
enc_type: conv_blstm
bidirectional_sum_fwd_bwd: true
enc_n_units: 512
enc_n_projs: 0
enc_n_layers: 5
subsample_type: drop
lc_chunk_size_left: -1  ### offline
lc_chunk_size_right: 40
attn_type: location
attn_conv_n_channels: 10
attn_conv_width: 201
attn_dim: 512
attn_n_heads: 1
dec_type: lstm
dec_n_units: 1024
dec_n_projs: 0
dec_n_layers: 1
dec_bottleneck_dim: 1024  ### this is effective
emb_dim: 512
tie_embedding: false
ctc_fc_list: "512"
### optimization
batch_size: 30
optimizer: adam
n_epochs: 25
convert_to_sgd_epoch: 100
print_step: 400
metric: edit_distance
lr: 1e-3
lr_decay_type: always
lr_decay_start_epoch: 10
lr_decay_rate: 0.85
lr_decay_patient_n_epochs: 0
early_stop_patient_n_epochs: 5
sort_stop_epoch: 100
eval_start_epoch: 1
warmup_start_lr: 1e-4
warmup_n_steps: 0
### initialization
param_init: 0.1
### regularization
clip_grad_norm: 5.0
dropout_in: 0.0
dropout_enc: 0.4
dropout_dec: 0.4
dropout_emb: 0.4
dropout_att: 0.0
weight_decay: 1e-6
ss_prob: 0.2
ss_type: constant
lsm_prob: 0.1
### MTL
ctc_weight: 0.3
ctc_lsm_prob: 0.1
mtl_per_batch: false
task_specific_layer: false
