# topology
lm_type: gated_conv_14B
emb_dim: 128
tie_embedding: false
# optimization
batch_size: 50
bptt: 200
optimizer: nesterov
n_epochs: 50
convert_to_sgd_epoch: 50
print_step: 400
lr: 1.0
lr_decay_start_epoch: 10
lr_decay_rate: 0.5
lr_decay_patient_n_epochs: 0
lr_decay_type: metric
stop_patient_n_epochs: 20
eval_start_epoch: 1
# initialization
param_init: 0.05
# regularization
clip_grad_norm: 0.1
dropout_in: 0.2
dropout_hidden: 0.2
dropout_out: 0.0
weight_decay: 1e-6
lsm_prob: 0.1
backward: false
adaptive_softmax: false
