parent: ./conf/attention/att_bgru.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # features
  num_stack: 1
  num_skip: 1

  # topology
  encoder_type: cnn
  conv_channels: [128, 128, 128, 128, 256, 256, 256, 256, 256, 256]
  conv_kernel_sizes:
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
  conv_strides:
    - [1, 2]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - [3, 1]
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  activation: prelu
  batch_norm: True
  encoder_num_layers: 0
  subsample_list:
    - False

  # optimization
  batch_size: 16
  optimizer: adam
  learning_rate: 1e-3
  convert_to_sgd_epoch: 20

  # regularization
  scheduled_sampling_ramp_max_step: 8000

  # annealing
  print_step: 40
