### topology
n_stacks: 1
n_skips: 1
max_n_frames: 1600
conv_in_channel: 1
conv_channels: "32_32"
conv_kernel_sizes: "(3,3)_(3,3)"
conv_strides: "(1,1)_(1,1)"
conv_poolings: "(2,2)_(2,2)"
conv_batch_norm: false
subsample: "1_1_1_1_1"
enc_type: conv_blstm
bidirectional_sum_fwd_bwd: true
enc_n_units: 16
enc_n_projs: 8
enc_n_layers: 1
subsample_type: drop
lc_chunk_size_left: -1  ### offline
lc_chunk_size_right: 40
dec_type: lstm
ctc_fc_list: "8"
### optimization
batch_size: 1
optimizer: adam
n_epochs: 4
convert_to_sgd_epoch: 100
print_step: 1
metric: edit_distance
lr: 1e-3
lr_decay_type: always
lr_decay_start_epoch: 2
lr_decay_rate: 0.85
lr_decay_patient_n_epochs: 0
early_stop_patient_n_epochs: 2
sort_stop_epoch: 100
eval_start_epoch: 2
warmup_start_lr: 1e-4
warmup_n_steps: 2
### initialization
param_init: 0.1
### regularization
clip_grad_norm: 5.0
dropout_in: 0.1
dropout_enc: 0.1
weight_decay: 1e-6
### MTL
ctc_weight: 1.0
ctc_lsm_prob: 0.1
mtl_per_batch: false
task_specific_layer: false
