### topology
n_stacks: 1
n_skips: 1
max_n_frames: 1600
conv_in_channel: 1
conv_channels: "32_32"
conv_kernel_sizes: "(3,3)_(3,3)"
conv_strides: "(1,1)_(1,1)"
conv_poolings: "(2,2)_(1,1)"
subsample: "1_2"
subsample_type: max_pool
enc_type: conv_conformer
conformer_kernel_size: 3
enc_n_layers: 1
transformer_enc_pe_type: relative  ###
transformer_enc_d_model: 8
transformer_enc_d_ff: 32
transformer_enc_n_heads: 4
dec_type: transformer
dec_n_layers: 1
transformer_dec_attn_type: scaled_dot
transformer_dec_pe_type: 1dconv3L
transformer_dec_d_model: 8
transformer_dec_d_ff: 32
transformer_dec_n_heads: 4
tie_embedding: false
ctc_fc_list: "8"
### optimization
batch_size: 1
optimizer: noam
n_epochs: 4
convert_to_sgd_epoch: 100
print_step: 1
metric: accuracy
lr_factor: 5.0
early_stop_patient_n_epochs: 2
shuffle_bucket: true
sort_stop_epoch: 100
eval_start_epoch: 2
warmup_n_steps: 2
accum_grad_n_steps: 2
### regularization
clip_grad_norm: 5.0
dropout_in: 0.1
dropout_enc: 0.1
dropout_dec: 0.1
dropout_emb: 0.1
dropout_att: 0.1
weight_decay: 1e-6
lsm_prob: 0.1
### MTL
ctc_weight: 0.3
ctc_lsm_prob: 0.1
mtl_per_batch: false
task_specific_layer: false
