### topology
n_stacks: 1
n_skips: 1
max_n_frames: 1600
conv_in_channel: 1
conv_channels: "32_32"
conv_kernel_sizes: "(3,3)_(3,3)"
conv_strides: "(1,1)_(1,1)"
conv_poolings: "(2,2)_(2,2)"
conv_batch_norm: false
conv_layer_norm: false
enc_type: conv_transformer
dec_type: transformer
enc_n_layers: 2
dec_n_layers: 2
transformer_attn_type: scaled_dot
transformer_enc_pe_type: none  ###
transformer_dec_pe_type: 1dconv3L  ### this is effective
transformer_d_model: 64
transformer_d_ff: 256
transformer_ffn_activation: relu
transformer_n_heads: 4
transformer_param_init: xavier_uniform
tie_embedding: false
ctc_fc_list: "512"
### optimization
batch_size: 1
optimizer: noam
n_epochs: 30
convert_to_sgd_epoch: 100
print_step: 1
metric: accuracy
lr_factor: 5.0
early_stop_patient_n_epochs: 5
shuffle_bucket: true  ### this is important
sort_stop_epoch: 100
eval_start_epoch: 10
warmup_n_steps: 10
accum_grad_n_steps: 2
### regularization
clip_grad_norm: 5.0
dropout_in: 0.1
dropout_enc: 0.1
dropout_dec: 0.1
dropout_emb: 0.1
dropout_att: 0.1
weight_decay: 1e-6
lsm_prob: 0.1
### MTL
ctc_weight: 0.3
ctc_lsm_prob: 0.1
mtl_per_batch: false
task_specific_layer: false
