### topology
n_stacks: 1
n_skips: 1
min_n_frames: 200  ###
max_n_frames: 1600
conv_in_channel: 1
conv_channels: "32_32"
conv_kernel_sizes: "(3,3)_(3,3)"
conv_strides: "(1,1)_(1,1)"
conv_poolings: "(2,2)_(2,2)"
conv_batch_norm: false
subsample: "1_1_1_1_1"
enc_type: conv_blstm
bidirectional_sum_fwd_bwd: true
enc_n_units: 512
enc_n_projs: 0
enc_n_layers: 5
subsample_type: drop
lc_chunk_size_left: 40
lc_chunk_size_right: 40
attn_type: mocha
mocha_chunk_size: 4
mocha_init_r: -4
mocha_eps: 1e-6
mocha_std: 1.0
mocha_1dconv: false
mocha_quantity_loss_weight: 0.0  ###
attn_sharpening_factor: 1.0
attn_dim: 512
attn_n_heads: 1
dec_type: lstm
dec_n_units: 1024
dec_n_projs: 0
dec_n_layers: 1
dec_bottleneck_dim: 1024  ### this is effective
emb_dim: 512
tie_embedding: false
ctc_fc_list: "512"
### optimization
batch_size: 1  ###
optimizer: sgd  ###
n_epochs: 3   ###
convert_to_sgd_epoch: 100
print_step: 800  ### 400->800
metric: edit_distance
lr: 3e-6  ###
lr_decay_type: always
lr_decay_start_epoch: 10
lr_decay_rate: 0.85
lr_decay_patient_n_epochs: 0
early_stop_patient_n_epochs: 5
shuffle_bucket: true  ### this is important
sort_stop_epoch: 100
eval_start_epoch: 1
warmup_start_lr: 1e-4
warmup_n_steps: 0  ###
### initialization
param_init: 0.1
### regularization
clip_grad_norm: 5.0
dropout_in: 0.0
dropout_enc: 0.0  ###
dropout_dec: 0.0  ###
dropout_emb: 0.0  ###
dropout_att: 0.0
weight_decay: 1e-6
lsm_prob: 0.0  ###
### MTL
ctc_weight: 0.0  ###
ctc_lsm_prob: 0.0  ###
mtl_per_batch: false
task_specific_layer: false
### MBR
mbr_training: true
mbr_ce_weight: 0.01
recog_beam_width: 4
recog_softmax_smoothing: 0.8
recog_length_norm: false
# recog_chunk_sync: true
