### topology
n_stacks: 1
n_skips: 1
max_n_frames: 2000
input_noise_std: 0
conv_in_channel: 3
conv_channels: "32_32"
conv_kernel_sizes: "(3,3)_(3,3)"
conv_strides: "(1,1)_(1,1)"
conv_poolings: "(1,1)_(1,1)"
conv_batch_norm: false
subsample: "1_1_1_1_1"
enc_type: blstm
bidirectional_sum_fwd_bwd: false
enc_n_units: 256
enc_n_projs: 0
enc_n_layers: 5
subsample_type: drop
attn_type: location
attn_conv_n_channels: 10
attn_conv_width: 201
attn_dim: 256
attn_n_heads: 1
dec_type: lstm
dec_n_units: 256
dec_n_projs: 0
dec_n_layers: 1
dec_bottleneck_dim: 256
emb_dim: 256
tie_embedding: false
ctc_fc_list: ""
### optimization
batch_size: 32
optimizer: adam
n_epochs: 100
convert_to_sgd_epoch: 90
print_step: 20
metric: edit_distance
lr: 1e-3
lr_decay_type: always
lr_decay_start_epoch: 20
lr_decay_rate: 0.97
lr_decay_patient_n_epochs: 0
early_stop_patient_n_epochs: 20
sort_stop_epoch: 100
eval_start_epoch: 20
warmup_start_lr: 1e-4
warmup_n_steps: 0
### initialization
param_init: 0.1
### regularization
clip_grad_norm: 5.0
dropout_in: 0.2
dropout_enc: 0.5
dropout_dec: 0.2
dropout_emb: 0.2
dropout_att: 0.0
weight_decay: 1e-6
ss_prob: 0.0
ss_type: constant
lsm_prob: 0.0
### MTL
ctc_weight: 0.0
ctc_lsm_prob: 0.0
mtl_per_batch: false
task_specific_layer: false
