# topology
lm_type: gated_conv_custom
kernel_size: 4
n_units: 1024
n_projs: 512
n_layers: 6
emb_dim: 300
tie_embedding: false
# optimization
batch_size: 50
bptt: 200
optimizer: nesterov
n_epochs: 100
convert_to_sgd_epoch: 100
print_step: 100
lr: 2.0
lr_decay_start_epoch: 10
lr_decay_rate: 0.75
lr_decay_patient_n_epochs: 0
# lr_decay_type: epoch
lr_decay_type: metric
early_stop_patient_n_epochs: 20
eval_start_epoch: 1
# initialization
param_init: 0.05
# regularization
clip_grad_norm: 0.1
dropout_in: 0.2
dropout_hidden: 0.5
dropout_out: 0.0
weight_decay: 1e-6
adaptive_softmax: true
