# topology
lm_type: lstm
n_units: 1024
n_projs: 0
n_layers: 2
emb_dim: 1024
tie_embedding: true
residual: true
use_glu: true
# optimization
batch_size: 20
bptt: 30
optimizer: adam
n_epochs: 50
convert_to_sgd_epoch: 100
print_step: 200
lr: 1e-3
lr_decay_start_epoch: 10
lr_decay_rate: 0.9
lr_decay_patient_n_epochs: 0
lr_decay_type: always
early_stop_patient_n_epochs: 10
eval_start_epoch: 1
# initialization
param_init: 0.05
# regularization
clip_grad_norm: 0.1
dropout_in: 0.2
dropout_hidden: 0.5
dropout_out: 0.0
weight_decay: 1e-6
lsm_prob: 0.0
adaptive_softmax: false
