# topology
lm_type: transformer_xl
n_layers: 12
transformer_d_model: 512
transformer_d_ff: 2048
transformer_n_heads: 8
tie_embedding: true
# optimization
batch_size: 24
bptt: 200
mem_len: 200
optimizer: noam
n_epochs: 50
convert_to_sgd_epoch: 100
print_step: 200
lr_factor: 1.0
early_stop_patient_n_epochs: 5
eval_start_epoch: 1
warmup_n_steps: 4000
accum_grad_n_steps: 4
# regularization
clip_grad_norm: 1.0
dropout_in: 0.1
dropout_hidden: 0.3
dropout_out: 0.0
dropout_att: 0.1
dropout_layer: 0.0
weight_decay: 1e-6
lsm_prob: 0.1  ###
adaptive_softmax: false
