# topology
lm_type: transformer
transformer_d_model: 512
transformer_d_ff: 2048
n_layers: 6
transformer_attn_type: scaled_dot
transformer_n_heads: 8
transformer_pe_type: add
tie_embedding: true
# optimization
batch_size: 32
bptt: 200
optimizer: noam
n_epochs: 100
convert_to_sgd_epoch: 100
print_step: 200
lr_factor: 10.0
early_stop_patient_n_epochs: 5
eval_start_epoch: 1
warmup_n_steps: 4000
accum_grad_n_steps: 2
# regularization
clip_grad_norm: 1.0
dropout_in: 0.1
dropout_hidden: 0.3
dropout_out: 0.0
dropout_att: 0.1
weight_decay: 1e-6
lsm_prob: 0.0
backward: false
adaptive_softmax: false
